apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-retail-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abc-retail
  template:
    metadata:
      labels:
        app: abc-retail
    spec:
      containers:
      - name: abc-retail-container
        image: kareem9263/abc-retail:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred


