apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-retail-deployment
  namespace: default    # ✅ Add this line if missing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abc-retail
  template:
    metadata:
      labels:
        app: abc-retail
    spec:
      containers:
      - name: abc-retail
        image: kareem9263/abc-retail:latest
        ports:
        - containerPort: 8080

