apiVersion: v1
kind: Service
metadata:
  name: abc-retail-service
  namespace: default     # ✅ Add this line
spec:
  type: NodePort
  selector:
    app: abc-retail
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008

